name: Run Unit Tests and Linting, and Block Pull Request

on:
  pull_request:
    branches:
      - main  
  workflow_dispatch:  # Add workflow_dispatch to allow manual triggering

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Run Unit Tests
        run: python3 unit_tests.py
        continue-on-error: true  # Continue even if tests fail, we'll check the status later

      - name: Run Linter
        run: pylint .
        continue-on-error: true  # Continue even if linting fails, we'll check the status later

      - name: Check Test and Lint Results
        run: exit $(($? + $?))
        # This will exit with a non-zero status if any of the previous steps failed

      - name: Create Pull Request
        if: always()
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          title: Unit Tests and Linting
          base: main
